services:
  - type: web
    name: password-reset-backend
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://password-rest.onrender.com
      - key: MONGODB_URI
        fromConnectionString: password_reset_app
